version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '01:23'
      timezone: Europe/Warsaw
    labels:
      - dependencies
      - actions
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
      time: '00:12'
      timezone: Europe/Warsaw
    labels:
      - dependencies
      - libs
