language: java

jdk:
  - openjdk11

script:
  - mvn -B clean install -Prun-its

addons:
  sonarcloud:
    organization: 'wiiitek-github'
    token:
      secure: 'EQN51imuWCsPDDZCG2cd/4TzhCpK1pRUJQl09vZaWyAxujvRppiP9HREN1QQUxpEeKFso2hVXIh6cfa4CXnUb1PJPmJSVS/z8+LXJC9M3e0xk6AxkDWc3cJYyfa7Ga2BKESVhVZlinskxQxk2LXeQAFWux2z4huYfk2Rq97ApPPIf7OrxyMAIiPHYc4n/IdOUG5tlVmTG8T+YxVCzKGEF+iuITp7rPj7Dvr4uqwm4+g1962S8ONLMZZ4n0kQUYiP+viPd5Myr4z7QuHrUln8YRKhVtvJnKX5Ing15dNPg/Yt0WKlETeXHdyw4KI76C92lpsNgF1IAEfNGrrOM+9TG/rtjl/vNX/OE1912z5y+bpmQf0UQ2+dkcS0JsMWcVEMlvUR+h5t2RBxQj7jGXq1blJIP6xs32wmnBg1wb8muvUsPULN45zFaTBZyEDMG9Q23pGPdGkTURuHnqRuDUL6R0H1k2l0yXecHPmcDNq/eP9IDqH5PJJW6W9dT3/Hr7Y8u1bqSrEB/tyzzz9TbuGtAMn04eziKX7nxUOql+fgXvt0BxTqiu+Chd7XMtNeWt5LlTlsPWxS/ALXYwHw8Pkyy4L7Gp/ZqSr2owTDrGcLcCjYrTO0+JoiyqTK4ipGOwUx5e4HvTFCof59Dum5tQQgF7rFCQkPa0sTEJGxKUQWUp8='

# see
# https://docs.travis-ci.com/user/build-stages#Build-Stages-and-Build-Matrix-Expansion
jobs:
  include:
    - stage: sonar
      jdk: openjdk11
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
        - mvn sonar:sonar -Dsonar.projectKey=pl.kubiczak:jade-to-filters-maven-plugin