language: java
jdk:
  - openjdk6
  - openjdk7
  - openjdk8
  - oraclejdk7
  - oraclejdk8
os:
  - linux
  - osx

dist:
  - precise

matrix:
  include:
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk6
